#!/usr/bin/env bash
# Generated by amplifier-bundle-autoharness — do not edit directly
# =============================================================================
# Harness Machine Health Monitor
# Runs every 10 minutes via cron. Detects failure patterns, auto-remediates
# common issues (permission healing, orphaned work, stale STATE.yaml),
# and logs results.
# NOTE: No set -euo pipefail — a monitor that dies on errors is worse than useless.
# All errors are handled explicitly with || true and 2>/dev/null guards.
#
# Run via cron every 10 minutes:
#   */10 * * * * /path/to/harness-machine-monitor.sh
# =============================================================================

PROJECT_DIR="{{project_dir}}"
MONITOR_LOG="$PROJECT_DIR/harness-machine-monitor.log"
CONTAINER="{{container_name}}"
IMAGE_NAME="{{image_name}}"
MAX_LOG_LINES=500

log() {
    echo "[$(date -u '+%Y-%m-%d %H:%M:%S UTC')] $*" >> "$MONITOR_LOG"
}

# -- Log rotation --------------------------------------------------------------
if [ -f "$MONITOR_LOG" ] && [ "$(wc -l < "$MONITOR_LOG")" -gt "$MAX_LOG_LINES" ]; then
    tail -200 "$MONITOR_LOG" > "$MONITOR_LOG.tmp"
    mv "$MONITOR_LOG.tmp" "$MONITOR_LOG"
fi

log "--- monitor check ---"

# -- Permission self-healing ---------------------------------------------------
# Docker can create files owned by the container user. Fix ownership so the host
# cron user can operate on these files. Uses the container image to chown (it
# has the right perms to write those files in the first place).

# Heal monitor log
if [ -f "$MONITOR_LOG" ] && [ ! -w "$MONITOR_LOG" ]; then
    docker run --rm -v "$PROJECT_DIR:$PROJECT_DIR" -w "$PROJECT_DIR" \
        --entrypoint bash "$IMAGE_NAME" \
        -c "chown $(id -u):$(id -g) $MONITOR_LOG" 2>/dev/null || true
    log "HEALED: monitor log ownership"
fi

# Heal .git/objects (Docker commits can create root-owned objects)
ROOT_OBJECTS=$(find "$PROJECT_DIR/.git/objects" -not -user "$(whoami)" 2>/dev/null | head -1)
if [ -n "$ROOT_OBJECTS" ]; then
    docker run --rm -v "$PROJECT_DIR:$PROJECT_DIR" -w "$PROJECT_DIR" \
        --entrypoint bash "$IMAGE_NAME" \
        -c "chown -R $(id -u):$(id -g) .git/" 2>/dev/null || true
    log "HEALED: .git ownership"
fi

# -- Container status ----------------------------------------------------------
# NOTE: {{.State.Status}} is a Docker Go template string -- NOT a machine template variable.
container_status=$(docker inspect -f '{{.State.Status}}' "$CONTAINER" 2>/dev/null || echo "missing")

# -- Auto-commit orphaned work -------------------------------------------------
# If the container stopped with uncommitted changes, save the work before we
# potentially exit. This prevents data loss on crash/restart cycles.
cd "$PROJECT_DIR" 2>/dev/null || true
DIRTY=$(git status --porcelain 2>/dev/null | head -1)
if [ -n "$DIRTY" ] && [ "$container_status" != "running" ]; then
    # Heal source file ownership first so git can stage everything
    for dir in .harness-machine harnesses src docs; do
        if [ -d "$PROJECT_DIR/$dir" ]; then
            ROOT_SRC=$(find "$PROJECT_DIR/$dir" -not -user "$(whoami)" 2>/dev/null | head -1)
            if [ -n "$ROOT_SRC" ]; then
                docker run --rm -v "$PROJECT_DIR:$PROJECT_DIR" -w "$PROJECT_DIR" \
                    --entrypoint bash "$IMAGE_NAME" \
                    -c "chown -R $(id -u):$(id -g) $dir/" 2>/dev/null || true
            fi
        fi
    done
    git add -A 2>/dev/null || true
    git commit -m "chore: auto-save orphaned harness work (monitor recovery)" 2>/dev/null || true
    log "AUTO-COMMIT: saved orphaned work from stopped container"
fi

# -- STATE.yaml-aware status ---------------------------------------------------
# Parse STATE.yaml for environment progress and blocker counts. Also resets any
# environments stuck in 'in-progress' when the container is down (stale state).
if [ -f "$PROJECT_DIR/STATE.yaml" ]; then
    _state_vars=$(python3 -c "
import yaml, sys
try:
    state = yaml.safe_load(open('$PROJECT_DIR/STATE.yaml'))
    environments = state.get('environments', {})
    remaining = sum(1 for e in environments.values() if isinstance(e, dict) and e.get('status') in ('ready', 'in-progress', 'blocked'))
    blockers = len(state.get('blockers', []))
    in_progress = [k for k, v in environments.items() if isinstance(v, dict) and v.get('status') == 'in-progress']
    print('REMAINING=' + str(remaining))
    print('BLOCKERS=' + str(blockers))
    print('IN_PROGRESS=' + str(len(in_progress)))
except Exception:
    print('REMAINING=?')
    print('BLOCKERS=?')
    print('IN_PROGRESS=?')
" 2>/dev/null) || true
    eval "${_state_vars:-REMAINING=?}" 2>/dev/null || true
    REMAINING="${REMAINING:-?}"
    BLOCKERS="${BLOCKERS:-?}"
    IN_PROGRESS="${IN_PROGRESS:-?}"
    log "STATE: remaining=$REMAINING blockers=$BLOCKERS in_progress=$IN_PROGRESS"

    # Reset stale in-progress environments if the container is down
    if [ "$container_status" != "running" ] && [ "$IN_PROGRESS" != "?" ] && [ "$IN_PROGRESS" -gt 0 ] 2>/dev/null; then
        python3 -c "
import yaml
state = yaml.safe_load(open('$PROJECT_DIR/STATE.yaml'))
changed = False
for k, v in state.get('environments', {}).items():
    if isinstance(v, dict) and v.get('status') == 'in-progress':
        v['status'] = 'ready'
        changed = True
if changed:
    with open('$PROJECT_DIR/STATE.yaml', 'w') as f:
        yaml.dump(state, f, default_flow_style=False, sort_keys=False)
" 2>/dev/null && log "HEALED: reset stale in-progress environments to ready"
    fi
fi

# -- Blocker detection ---------------------------------------------------------
has_blockers="no"
if [ -f "$PROJECT_DIR/STATE.yaml" ]; then
    blocker_section=$(sed -n '/^blockers:/,/^[a-z]/p' "$PROJECT_DIR/STATE.yaml" 2>/dev/null)
    if echo "$blocker_section" | grep -q "description:"; then
        has_blockers="yes"
    fi
fi

# -- Exit early if container is not running ------------------------------------
if [ "$container_status" != "running" ]; then
    log "ALERT: Container not running (status: $container_status)"
    log "--- monitor check end ---"
    exit 0
fi

# -- Current stats -------------------------------------------------------------
# NOTE: {{.CPUPerc}}, {{.MemUsage}} are Docker Go template strings -- NOT machine template variables.
cpu=$(docker stats "$CONTAINER" --no-stream --format '{{.CPUPerc}}' 2>/dev/null || echo "?")
mem=$(docker stats "$CONTAINER" --no-stream --format '{{.MemUsage}}' 2>/dev/null || echo "?")
head_commit=$(cd "$PROJECT_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "?")
unpushed=$(cd "$PROJECT_DIR" && git rev-list --count @{u}..HEAD 2>/dev/null || echo "?")

# -- Silent recipe loop detection ----------------------------------------------
last_attempt=$(docker logs "$CONTAINER" --tail 50 2>&1 | grep -oP 'attempt \K\d+' | tail -1)
recipe_fail_count=$(docker logs "$CONTAINER" --tail 100 2>&1 | grep -c "Recipe execution failed" || true)

# -- Heartbeat freshness -------------------------------------------------------
heartbeat_age="n/a"
if [ -f "$PROJECT_DIR/.harness-machine-heartbeat" ]; then
    heartbeat_age=$(( $(date +%s) - $(stat -f %m "$PROJECT_DIR/.harness-machine-heartbeat" 2>/dev/null || stat -c %Y "$PROJECT_DIR/.harness-machine-heartbeat" 2>/dev/null || echo 0) ))
fi

# -- HEAD movement tracking ----------------------------------------------------
LAST_HEAD_FILE="$PROJECT_DIR/.monitor-last-head"
last_head=$(cat "$LAST_HEAD_FILE" 2>/dev/null || echo "")
head_moved="no"
if [ "$head_commit" != "$last_head" ] && [ -n "$last_head" ]; then
    head_moved="yes"
fi
echo "$head_commit" > "$LAST_HEAD_FILE"

# -- Unpushed commit annotation ------------------------------------------------
push_alert=""
if [ "$unpushed" != "?" ] && [ "$unpushed" -gt 10 ]; then
    push_alert=" ALERT:unpushed>10"
fi

# -- Status line ---------------------------------------------------------------
log "STATUS: cpu=$cpu mem=$mem head=$head_commit unpushed=$unpushed moved=$head_moved attempt=$last_attempt recipe_fails=$recipe_fail_count heartbeat_age=${heartbeat_age}s blockers=$has_blockers$push_alert"

# ==============================================================================
# Pattern detections + auto-remediation
# ==============================================================================

# Pattern A: Silent recipe loop (high failure count + HEAD not moving)
if [ "$recipe_fail_count" -gt 5 ] && [ "$head_moved" = "no" ]; then
    log "ALERT: SILENT RECIPE LOOP detected ($recipe_fail_count failures in recent logs, HEAD not moving)"
    log "ACTION: Check 'docker logs $CONTAINER --tail 30' for the failing step"
fi

# Pattern B: Cloudflare backoff (0% CPU but heartbeat is fresh)
if [ "$cpu" = "0.00%" ] && [ "$heartbeat_age" != "n/a" ] && [ "$heartbeat_age" -lt 3600 ]; then
    log "INFO: Entrypoint alive (heartbeat ${heartbeat_age}s ago) but 0% CPU — likely CF backoff"
fi

# Pattern C: Stale blockers — apply blocker aging policy
# Walk every blocker that has a 'since' epoch field.
# Age = current_epoch - blocker.since. Log with escalating urgency.
# Auto-defer environments with blockers aged 20+ epochs.
#
# Aging policy:
#   1-5 epochs   → INFO
#   6-10 epochs  → WARNING
#   11-19 epochs → CRITICAL
#   20+ epochs   → CRITICAL + AUTO-DEFER
if [ "$has_blockers" = "yes" ]; then
    _aging_output=$(python3 -c "
import yaml, sys
try:
    state = yaml.safe_load(open('$PROJECT_DIR/STATE.yaml'))
except Exception:
    sys.exit(0)

environments   = state.get('environments') or {}
current_epoch  = state.get('epoch', 0)
changed        = False
lines          = []
no_since_count = 0

# Check top-level blockers
for blocker in (state.get('blockers') or []):
    if not isinstance(blocker, dict):
        continue
    since = blocker.get('since')
    if since is None:
        no_since_count += 1
        continue
    try:
        age = int(current_epoch) - int(since)
    except (ValueError, TypeError):
        no_since_count += 1
        continue
    if age < 1:
        continue
    label = str(blocker.get('description') or 'unknown')[:60]
    if age >= 20:
        lines.append(
            f'CRITICAL: Blocker \"{label}\" stale ({age} epochs) - auto-defer recommended'
        )
    elif age >= 11:
        lines.append(
            f'CRITICAL: Blocker \"{label}\" stale ({age} epochs) - requires manual review'
        )
    elif age >= 6:
        lines.append(
            f'WARNING: Blocker \"{label}\" aging ({age} epochs) - may need human attention'
        )
    else:
        lines.append(f'INFO: Blocker \"{label}\" present for {age} epochs')

# Check per-environment blockers (if environments have their own blocker lists)
for env_name, env_data in (environments.items() if isinstance(environments, dict) else []):
    if not isinstance(env_data, dict):
        continue
    for blocker in (env_data.get('blockers') or []):
        if not isinstance(blocker, dict):
            continue
        since = blocker.get('since')
        if since is None:
            no_since_count += 1
            continue
        try:
            age = int(current_epoch) - int(since)
        except (ValueError, TypeError):
            no_since_count += 1
            continue
        if age < 1:
            continue
        label = str(blocker.get('description') or blocker.get('type') or 'unknown')[:60]
        if age >= 20:
            lines.append(
                f'CRITICAL: Blocker \"{label}\" stale ({age} epochs)'
                f' - auto-deferring environment \"{env_name}\"'
            )
            lines.append(
                f'AUTO-DEFER: Environment \"{env_name}\" moved to deferred'
                f' (blocker aged {age} epochs)'
            )
            env_data['status'] = 'deferred'
            changed = True
        elif age >= 11:
            lines.append(
                f'CRITICAL: Blocker \"{label}\" stale ({age} epochs)'
                f' - recommend manual review or auto-defer'
            )
        elif age >= 6:
            lines.append(
                f'WARNING: Blocker \"{label}\" aging ({age} epochs)'
                f' - may need human attention'
            )
        else:
            lines.append(f'INFO: Blocker \"{label}\" present for {age} epochs (env: {env_name})')

if changed:
    with open('$PROJECT_DIR/STATE.yaml', 'w') as f:
        yaml.dump(state, f, default_flow_style=False, sort_keys=False)

if not lines and no_since_count > 0:
    lines.append(
        'ALERT: STATE.yaml has active blockers (no epoch data)'
        ' - machine may need human attention'
    )

print('\n'.join(lines))
" 2>/dev/null) || true

    if [ -n "$_aging_output" ]; then
        while IFS= read -r _aging_line; do
            [ -n "$_aging_line" ] && log "$_aging_line"
        done <<< "$_aging_output"
    else
        log "ALERT: STATE.yaml has active blockers — machine may need human attention"
    fi
fi

# Pattern D: Dead entrypoint (stale heartbeat + 0% CPU)
if [ "$cpu" = "0.00%" ] && [ "$heartbeat_age" != "n/a" ] && [ "$heartbeat_age" -gt 3600 ]; then
    log "ALERT: Entrypoint appears dead (heartbeat ${heartbeat_age}s stale, 0% CPU)"
fi

# Pattern E: Unpushed commits — auto-push if threshold exceeded
if [ "$unpushed" != "?" ] && [ "$unpushed" -gt 10 ]; then
    log "AUTO-FIX: $unpushed unpushed commits. Pushing..."
    cd "$PROJECT_DIR" 2>/dev/null || true
    git stash 2>/dev/null || true
    git pull --rebase 2>/dev/null || true
    if git push 2>/dev/null; then
        NEW_UNPUSHED=$(git rev-list --count @{u}..HEAD 2>/dev/null || echo "?")
        log "AUTO-FIX: Push successful. $NEW_UNPUSHED commits remaining."
    else
        log "AUTO-FIX: Push FAILED. SSH agent may be dead or no network."
    fi
    git stash pop 2>/dev/null || true
fi

log "--- monitor check end ---"
