# =============================================================================
# Generated by amplifier-bundle-autoharness — do not edit directly
# Amplifier Harness Machine Container: {{project_name}}
#
# Sandboxed environment for autonomous constraint harness generation.
# Agents have bash access but can only affect the bind-mounted project directory.
#
# Build:  docker compose -f docker-compose.harness-machine.yaml build
# Run:    docker compose -f docker-compose.harness-machine.yaml up -d
# Shell:  docker compose -f docker-compose.harness-machine.yaml exec harness-machine bash
#
# ---- Template variables ------------------------------------------------------
#
#   {{base_image}}           — Docker base image
#                              Python-primary: python:3.12-slim (default)
#
#   {{user_uid}}             — Host user UID (bind-mount permission compatibility)
#   {{user_gid}}             — Host user GID (bind-mount permission compatibility)
#   {{username}}             — Host username; must equal $(basename {{user_home}})
#   {{user_home}}            — Absolute home path matching the HOST user's $HOME
#                              e.g. /home/samschillace
#                              MUST match host path — bind-mounts use this path
#
#   {{project_name}}         — Short project identifier, e.g. chess-harness
#   {{project_dir}}          — Absolute path to project root
#                              e.g. /home/samschillace/dev/my-harness-project
#
#   {{uv_version}}           — Pinned uv version, e.g. 0.10.4
#                              Never use :latest — version skew breaks lockfiles
#
#   {{system_packages}}      — Extra apt packages, space-separated (may be empty)
#                              Compiled environment runners may need: build-essential
#                              TextArena/Gymnasium: python3-dev
#
#   {{node_setup}}           — Multi-line Node.js setup block, or empty string
#                              Leave empty for Python-only harness projects
#
#   {{python_dev_tools}}     — uv tool install lines for Python dev tools, or empty
#                              Example: RUN uv tool install ruff && uv tool install pyright
#
#   {{extra_pip_packages}}   — Additional system-python pip packages beyond pyyaml
#                              e.g. gymnasium textarena (for harness evaluation)
#
#   {{install_deps_block}}   — NOT used here — project source is bind-mounted at
#                              runtime, not available during docker build.
#                              Used in entrypoint.sh.
# =============================================================================

FROM {{base_image}}

# -- System dependencies -------------------------------------------------------
# git            — commits, branch ops, safe.directory config
# curl           — API pre-flight check in entrypoint; nodesource / apt key scripts
# ca-certificates — HTTPS for git+https Amplifier install and LLM API calls
# jq             — used in recipe bash steps for JSON parsing
# {{system_packages}} — project-specific extras; placed inline to avoid an
#                       orphaned backslash when the variable is empty
RUN apt-get update && apt-get install -y --no-install-recommends \
        openssh-client \
        git \
        curl \
        ca-certificates \
        jq {{system_packages}} \
    && rm -rf /var/lib/apt/lists/*

# -- Node.js setup (optional) --------------------------------------------------
# Leave {{node_setup}} empty for Python-only harness projects.
{{node_setup}}

# -- System Python: pyyaml + extras --------------------------------------------
# Recipe bash steps call `python3 -c "import yaml; ..."` to read/write STATE.yaml.
# pyyaml MUST live in system python3 — outside any project venv — so it is
# available unconditionally in every bash step, even before `uv sync` runs.
#
# --break-system-packages: required on Debian/Ubuntu base images (PEP 668
# "externally managed environment"). Harmless on official python:* images.
#
# {{extra_pip_packages}} may be empty — trailing space on the install line is fine.
RUN python3 -m pip install --no-cache-dir --break-system-packages \
        pyyaml {{extra_pip_packages}}

# -- uv (pinned version) -------------------------------------------------------
# Copied directly from the official uv image — no curl|bash, no apt package.
# Pinned to {{uv_version}} to match the host and keep uv.lock compatible.
# Update intentionally when you want to upgrade; never set :latest.
COPY --from=ghcr.io/astral-sh/uv:{{uv_version}} /uv /uvx /usr/local/bin/

# -- Non-root user (UID/GID must match host for bind-mount permissions) --------
# Running as root causes permission issues: files written to the bind-mounted
# project directory become root-owned, blocking host-side cron monitors,
# `git status`, and any tooling that runs as the unprivileged host user.
#
# {{user_home}} MUST equal the host user's $HOME so that bind-mounted paths
# (project dir, .ssh/known_hosts) resolve identically inside the container.
# {{username}} must equal $(basename {{user_home}}).
ARG USER_UID={{user_uid}}
ARG USER_GID={{user_gid}}

# Idempotent: -f skips if group/user already exists (e.g. node base images
# that ship UID 1000 as 'node').  The || true handles both the -f flag
# (which isn't universal across addgroup/adduser implementations) and the
# case where the UID is already claimed under a different name.
RUN groupadd -f -g ${USER_GID} {{username}} 2>/dev/null || true \
    && id -u {{username}} >/dev/null 2>&1 \
    || useradd -m -u ${USER_UID} -g ${USER_GID} -s /bin/bash \
         -d {{user_home}} {{username}}

# -- Install Amplifier as the non-root user ------------------------------------
# Installing as root leaves shebangs pointing at /root/.local/... which breaks
# after the USER switch.  We install as {{username}} so uv puts binaries in
# {{user_home}}/.local/bin/ with correct shebangs.
USER {{username}}
ENV PATH="{{user_home}}/.local/bin:${PATH}"

RUN uv tool install amplifier --from "git+https://github.com/microsoft/amplifier"

# -- Python dev tools (optional) -----------------------------------------------
# ruff, pyright, pytest, etc.  Leave {{python_dev_tools}} empty to skip.
{{python_dev_tools}}

# -- Git identity for container commits ----------------------------------------
# safe.directory allows git to operate on the bind-mounted project dir
# (owned by host UID, which matches container UID).
# URL rewrite: the container has SSH agent forwarding but no HTTPS credential
# helper, so all github.com HTTPS URLs are rewritten to SSH.  This ensures
# `amplifier` bundle/module clones use the forwarded SSH key transparently.
RUN git config --global user.name "{{project_name}} Harness Machine" && \
    git config --global user.email "harness-machine@{{project_name}}.local" && \
    git config --global --add safe.directory {{project_dir}} && \
    git config --global url."git@github.com:".insteadOf "https://github.com/"

# -- SSH directory for known_hosts bind-mount ----------------------------------
RUN mkdir -p {{user_home}}/.ssh && chmod 700 {{user_home}}/.ssh

# -- Pre-create .amplifier dir for named volume --------------------------------
# Docker named volumes inherit ownership from the container's directory at
# first mount.  If .amplifier doesn't exist, the volume is created as root.
# Creating it here ensures the named volume starts with correct ownership.
RUN mkdir -p {{user_home}}/.amplifier

# -- Entrypoint ----------------------------------------------------------------
COPY --chown={{user_uid}}:{{user_gid}} scripts/entrypoint.sh {{user_home}}/entrypoint.sh
RUN chmod +x {{user_home}}/entrypoint.sh

WORKDIR {{project_dir}}

ENTRYPOINT ["{{user_home}}/entrypoint.sh"]
CMD ["amplifier", "tool", "invoke", "recipes", "operation=execute", \
     "recipe_path={{project_dir}}/.harness-machine/build.yaml"]
